### ISSUE TITLE
community "work as" dropdown needs to be wider on Invite New Members page

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#2933]
Not sure if this is new since the last code push or not. Currently cuts off usernames longer than 15 characters. Viewing in Chrome.

<img width="719" alt="Screen Shot 2022-03-17 at 3 33 41 PM" src="https://user-images.githubusercontent.com/1976742/158890473-f1c0a2d6-7750-4651-91bf-3ff5df58cb11.png">

**Comment by momijizukamori** [comment]
Okay, doing some digging, and this appears to be due to some changes we made to default styling for the authas html combined with the way it renders (or is supposed to render, anyway) in foundationized pages. That said, this and the other community management pages are the only place I can find so far that's actually using the foundationized authas? Everything else seems to use the old style, even when there's foundation CSS on the page
